name: Triggers
run-name: ยก3 event triggers!
on:
  push:
    branches: ['main', 'aprendiendo-**']
    paths: ['**.yml']
  pull_request:
    types: [opened, edited, labeled]
    branches: ['main', 'aprendiendo-**']
    paths:
      - '**.js'
  schedule:
    - cron: '59 13 * * *'

jobs:
  job-t:
    runs-on: ubuntu-latest
    steps:
      - name: Clonar Repo en el Runner
        uses: actions/checkout@v4

      - name: Setup Node Enviroment
        uses: actions/setup-node@v4
        with: 
          node-version: '20.x'
      
      - name: Define Variable IP
        id: ip
        uses: haythem/public-ip@v1.3
        
      - name: Define Variable USERNAME   
        run: echo "USERNAME=${{ github.actor }}" >> $GITHUB_ENV
      
      - name: Run multi-line script
        run: |
          echo "Hello from IP: ${{ steps.ip.outputs.ipv4 }}"
          node main.js
